### ISSUE TITLE
When I update to the v0.11.0 , EOS-Studio can not work any more

### ISSUE THREAD

**Issue by LoAcer** [ObsidianLabs/EOS-Studio-Releases#1]
when I update to the v0.11.0 there always show a message box like below:
<img width="417" alt="5e45f2809f8af95b2f78cd3d0704627" src="https://user-images.githubusercontent.com/22309402/66465959-70439180-eab4-11e9-83d8-4a83906d42ba.png">

And I change another computer, it has the same problem.
This version cann't launch well on MacBook too. 

Then I  revert to the last version(v0.10.0)，there still has the message.

Is that a mistake  in EXE or anything I have done was  wrong.

By the way, there weren't desk D:\ on my  and  coworker's Computer!

**Comment by leonlianght** [comment]
Please re-install it and the issue should be gone.

**Comment by leonlianght** [comment]
Feel free to reopen if the problem is not solved.

**Comment by lagagain** [comment]
Linux version has the same problem. And now the version v0.11.0 seems like be retracted.

I download v0.10.0 on 9/30, and I haven't updated it to v0.11.0 by manual.  I found the directory `.cache/eos-studio-updater`, and I guess it auto-update, then makes the problem.

I revert the version 0.10.0 by re-download the version from the [page](https://github.com/ObsidianLabs/EOS-Studio-Desktop).  If someone has the same problem on Linux who can the same as me to use the old version.

**Comment by leonlianght** [comment]
> Linux version has the same problem. And now the version v0.11.0 seems like be retracted.
> 
> I download v0.10.0 on 9/30, and I haven't updated it to v0.11.0 by manual. I found the directory `.cache/eos-studio-updater`, and I guess it auto-update, then makes the problem.
> 
> I revert the version 0.10.0 by re-download the version from the [page](https://github.com/ObsidianLabs/EOS-Studio-Desktop). If someone has the same problem on Linux who can the same as me to use the old version.

We are fixing all the issues and will update it asap.

**Comment by leonlianght** [comment]
The release has updated, please try to download the new version https://github.com/ObsidianLabs/EOS-Studio-Releases/releases

**Comment by lagagain** [comment]
> The release has updated, please try to download the new version https://github.com/ObsidianLabs/EOS-Studio-Releases/releases

I received the message about the auto-update.  I agree and reopen, then it successfully runs now.

**Comment by LoAcer** [comment]
Thanks of All.  I notice that the new one is smaller than before And It runs very well.
