### ISSUE TITLE
Should include SHA256 hash for binary release

### ISSUE THREAD

**Issue by trmaphi** [ObsidianLabs/EOS-Studio-Releases#4]
# Description

For binary release, we should add SHA256 hash to confirm the integrity of binary. Thanks 🙏

**Comment by leonlianght** [comment]
Thanks for your suggestion!

**Comment by leonlianght** [comment]
Actually the latest*.yml files in the 'Assets' includes the sha512 checksums, you may manually verify it by `new Buffer(hash, 'hex').toString('base64')`
